server:
  port: 9297
spring :
  application :
    name : config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhijimi4807/config-server-properties.git
          clone-on-start: true